version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: | # create whl, remove 'convrsn' folder, install dependency - pytest library
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip install pipenv
            pipenv install build
            pipenv run python3 -m build
            rm -rf convrsn
            pipenv install pytest
            pipenv install dist/convrsn-0.1.1-py3-none-any.whl
      - run:
          command: | # Run test suite
            echo "Running test suite"
            pipenv run pytest
  test_pypi_publish:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: | # create whl, install twine and publish to Test PyPI
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip install pipenv
            pipenv install build
            pipenv run python3 -m build
            pipenv install twine
            pipenv run twine upload --repository testpypi dist/* --verbose
  pypi_publish:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: | # create whl, install twine and publish to PyPI
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip install pipenv
            pipenv install build
            pipenv run python3 -m build
            pipenv install twine
            pipenv run twine upload dist/* --verbose --password $TWINE_PROD_PASSWORD
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - develop
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - main
